version: '3.8'
services:
  db:
    image: postgres:16
    container_name: "postgres"
    networks:
      - common_network
    env_file:
      - .env
    volumes:
      - ~/app/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - common_network
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    expose:
      - "8000"

networks:
  common_network:
    name: common_network
    driver: bridge